/**
 * Booking v1 copy. English and Thai stay in the same keys.
 * Status words stay honest: a visit is planned, canceled, or done.
 * Never Confirmed, Reserved, or Booked — Become does not hold the clinic's chair.
 */
export const BOOKING_COPY = {
  en: {
    booking_lede: "Your own note of an upcoming visit. We don't reserve the clinic's chair.",
    booking_empty_title: "No visits planned",
    booking_empty_body: "We don't reserve the clinic's chair.",
    booking_plan: "Plan a visit",
    booking_message_clinic: "Message clinic",
    booking_nopack_title: "Add a package first",
    booking_nopack_body: "A visit stays tied to a package you already have.",
    booking_planned: "Planned",
    booking_canceled: "Canceled",
    booking_done: "Done",
    booking_message: "Message",
    booking_mark_done: "Done",
    booking_edit: "Edit",
    booking_cancel_visit: "Cancel visit",
    booking_cancel_confirm: "Cancel this visit? The clinic is not notified.",
    booking_keep: "Keep it",
    booking_success_title: "Visit planned",
    booking_success_body: "This isn't a confirmation from the clinic.",
    booking_package: "Package",
    booking_date: "Date",
    booking_time: "Time",
    booking_time_hint: "Recommended — so you remember when to go.",
    booking_notes: "Notes",
    booking_notes_ph: "Anything you want to remember",
    booking_remind: "Remind me",
    booking_message_after: "Message clinic after saving",
    booking_link: "Clinic booking link",
    booking_link_hint: "Optional. This opens the clinic's own page.",
    booking_link_invalid: "Use a full link that starts with https://",
    booking_expiry_warn: "This date is after the package expires. You can still save it.",
    booking_suggest_hint: "Suggested from your usual interval. Change it if you like.",
    booking_save: "Save visit",
    booking_saving: "Saving…",
    booking_read_only: "From your package",
    booking_sessions_left: "Sessions left",
    booking_choose_pack: "Choose an open package",
    booking_earlier: "Earlier",
    booking_menu: "More",
    booking_contact_title: "How should we reach this clinic?",
    booking_contact_body: "Become only opens a chat for a LINE ID or WhatsApp number you've saved. We never guess it.",
    booking_line_label: "LINE Official Account ID",
    booking_line_ph: "@clinicname",
    booking_wa_label: "WhatsApp number",
    booking_wa_ph: "971501234567",
    booking_open_chat: "Open chat",
    booking_no_channel: "Messaging follows your country: LINE in Thailand, WhatsApp in the UAE. Set currency to THB or AED, or add a country on your profile.",
    booking_which_clinic: "Which clinic?",
    booking_open_page: "Clinic page",
    booking_plan_sub: "A note for you. This isn't a confirmation from the clinic.",
    booking_edit_title: "Edit visit",
    booking_close: "Close",
    booking_loading: "Loading your visits…",
    booking_dismiss: "Dismiss",
    booking_journal: "Journal",
    booking_expires: "Expires",
  },
  th: {
    booking_lede: "บันทึกวันที่จะไปด้วยตัวเอง เราไม่ได้กันที่นั่งที่คลินิกให้",
    booking_empty_title: "ยังไม่มีนัดที่วางแผนไว้",
    booking_empty_body: "เราไม่ได้จองเก้าอี้ที่คลินิกให้",
    booking_plan: "วางแผนการไป",
    booking_message_clinic: "ทักคลินิก",
    booking_nopack_title: "เพิ่มแพ็กเกจก่อน",
    booking_nopack_body: "การไปผูกกับแพ็กเกจที่คุณมีอยู่แล้ว",
    booking_planned: "วางแผนแล้ว",
    booking_canceled: "ยกเลิกแล้ว",
    booking_done: "เสร็จแล้ว",
    booking_message: "ทัก",
    booking_mark_done: "เสร็จแล้ว",
    booking_edit: "แก้ไข",
    booking_cancel_visit: "ยกเลิกการไป",
    booking_cancel_confirm: "ยกเลิกการไปนี้ไหม คลินิกจะไม่ได้รับการแจ้ง",
    booking_keep: "เก็บไว้",
    booking_success_title: "วางแผนการไปแล้ว",
    booking_success_body: "นี่ไม่ใช่การยืนยันจากคลินิก",
    booking_package: "แพ็กเกจ",
    booking_date: "วันที่",
    booking_time: "เวลา",
    booking_time_hint: "แนะนำไว้ จะได้จำเวลาได้",
    booking_notes: "โน้ต",
    booking_notes_ph: "สิ่งที่อยากจำ",
    booking_remind: "เตือนฉัน",
    booking_message_after: "ทักคลินิกหลังบันทึก",
    booking_link: "ลิงก์จองของคลินิก",
    booking_link_hint: "ไม่บังคับ เปิดหน้าของคลินิกเอง",
    booking_link_invalid: "ใส่ลิงก์เต็มที่ขึ้นต้นด้วย https://",
    booking_expiry_warn: "วันนี้เลยวันหมดอายุของแพ็กเกจแล้ว ยังบันทึกได้",
    booking_suggest_hint: "แนะนำจากช่วงที่คุณไปปกติ เปลี่ยนได้",
    booking_save: "บันทึกการไป",
    booking_saving: "กำลังบันทึก…",
    booking_read_only: "จากแพ็กเกจของคุณ",
    booking_sessions_left: "ครั้งที่เหลือ",
    booking_choose_pack: "เลือกแพ็กเกจที่ยังใช้ได้",
    booking_earlier: "ก่อนหน้านี้",
    booking_menu: "เพิ่มเติม",
    booking_contact_title: "จะให้ทักคลินิกนี้อย่างไร",
    booking_contact_body: "Become เปิดแชทเฉพาะ LINE หรือ WhatsApp ที่คุณบันทึกไว้ เราไม่เดาให้",
    booking_line_label: "ไอดี LINE Official ของคลินิก",
    booking_line_ph: "@clinicname",
    booking_wa_label: "เบอร์ WhatsApp",
    booking_wa_ph: "971501234567",
    booking_open_chat: "เปิดแชท",
    booking_no_channel: "ทักคลินิกตามประเทศของคุณ ไทยใช้ LINE ยูเออีใช้ WhatsApp ตั้งสกุลเงินเป็น THB หรือ AED หรือใส่ประเทศในโปรไฟล์",
    booking_which_clinic: "คลินิกไหน",
    booking_open_page: "หน้าคลินิก",
    booking_plan_sub: "บันทึกไว้เตือนตัวเอง นี่ไม่ใช่การยืนยันจากคลินิก",
    booking_edit_title: "แก้ไขการไป",
    booking_close: "ปิด",
    booking_loading: "กำลังโหลดการไปของคุณ…",
    booking_dismiss: "ปิด",
    booking_journal: "บันทึก",
    booking_expires: "หมดอายุ",
  },
};

const FORBIDDEN_STATUS = /\b(confirmed|reserved|booked)\b/i;

/** Keys whose copy uses a clinic-confirmation status word. Empty means the copy is safe. */
export function findForbiddenStatusWords(copy) {
  const hits = [];
  Object.keys(copy || {}).forEach((lang) => {
    const block = copy[lang] || {};
    Object.keys(block).forEach((key) => {
      if (FORBIDDEN_STATUS.test(String(block[key]))) hits.push(`${lang}.${key}`);
    });
  });
  return hits;
}
